name: Zcash Radio — Refresh & Deploy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate cache slot
        id: cache_meta
        run: |
          SLOT="$(date -u +'%Y-%m-%d')-slot$(( $(date -u +%H) / 6 ))"
          echo "slot=$SLOT" >> "$GITHUB_OUTPUT"
          echo "CACHE_KEY=videos-json-$SLOT" >> "$GITHUB_ENV"

      - name: Restore cached videos.json
        id: restore_videos
        uses: actions/cache@v4
        with:
          path: public/videos.json
          key: ${{ env.CACHE_KEY }}
          restore-keys: videos-json-

      - name: Set up Rust toolchain
        if: steps.restore_videos.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@stable

      - name: Prime Rust build cache
        if: steps.restore_videos.outputs.cache-hit != 'true'
        uses: Swatinem/rust-cache@v2

      - name: Generate videos.json
        if: steps.restore_videos.outputs.cache-hit != 'true'
        run: cargo run --release

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Refresh ZEC stats
        run: python scripts/get-zec-stats.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
